services:
  server:
    build: ./server
    container_name: verteilte-server
    ports:
      - "6900:6900"
    environment:
      - PORT=6900
      - DATABASE_URL=postgres://user:password@db:5432/verteilte
    depends_on:
      - db
    networks:
      - verteilte-net

  db:
    image: postgres:15-alpine
    container_name: verteilte-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: verteilte
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/src/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - verteilte-net

volumes:
  postgres_data:


networks:
  verteilte-net:
    driver: bridge
