services:
  db:
    image: postgres:15-alpine
    container_name: verteilte-db
    network_mode: host
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: verteilte
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/src/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
